import ILanguage from '@/models/ILanguage';

export const LANGUAGE_LIST: ILanguage[] = [
	{ label: 'Angielski', key: 'en', userName: 'You' },
	{ label: 'Bułgarski', key: 'bg', userName: 'Вие' },
	{ label: 'Chiński', key: 'zh', userName: '你' },
	{ label: 'Czeski', key: 'cs', userName: 'Vy' },
	{ label: 'Duński', key: 'da', userName: 'Du' },
	{ label: 'Fiński', key: 'fi', userName: 'Sinä' },
	{ label: 'Francuski', key: 'fr', userName: 'Toi' },
	{ label: 'Grecki', key: 'el', userName: 'Εσείς' },
	{ label: 'Hindi', key: 'hi', userName: 'आप' },
	{ label: 'Hiszpański', key: 'es', userName: 'Tú' },
	{ label: 'Indonezyjski', key: 'id', userName: 'Anda' },
	{ label: 'Japoński', key: 'ja', userName: 'あなた' },
	{ label: 'Koreański', key: 'ko', userName: '너' },
	{ label: 'Malajski', key: 'ms', userName: 'Awak' },
	{ label: 'Niderlandzki', key: 'nl', userName: 'Jij' },
	{ label: 'Niemiecki', key: 'de', userName: 'Du' },
	{ label: 'Norweski', key: 'no', userName: 'Du' },
	{ label: 'Polski', key: 'pl', userName: 'Ty' },
	{ label: 'Portugalski', key: 'pt', userName: 'Tu' },
	{ label: 'Rumuński', key: 'ro', userName: 'Tu' },
	{ label: 'Ruski', key: 'ru', userName: 'Ты' },
	{ label: 'Słowacki', key: 'sk', userName: 'Vy' },
	{ label: 'Szwecki', key: 'sv', userName: 'Du' },
	{ label: 'Turecki', key: 'tr', userName: 'Sen' },
	{ label: 'Ukraiński', key: 'uk', userName: 'Ви' },
	{ label: 'Węgierski', key: 'hu', userName: 'Te' },
	{ label: 'Wietnamski', key: 'vi', userName: 'Bạn' },
	{ label: 'Włoski', key: 'it', userName: 'Voi' },
];
